# https://taskfile.dev
version: '3'

dotenv: ['.env']

tasks:
  init:
    desc: Initialize environment
    silent: true
    cmds:
      - echo init

  default:
   desc: default
   silent: true
   cmds:
     - task --list-all
