# https://taskfile.dev
version: '3'

tasks:
  init:
    desc: Initialize environment
    silent: true
    cmds:
      - echo init

  build:
    desc: build application
    silent: true
    cmds:
      - go build

  run:
    desc: Run application
    silent: true
    cmds:
      - go run main.go

  default:
   desc: default
   silent: true
   cmds:
     - task --list-all
